/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import org.flexunit.internals.TraceListener;
	import org.flexunit.listeners.CIListener;
	import org.flexunit.runner.FlexUnitCore;
	
	import test.RobotlegGallaryTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var core:FlexUnitCore;
	
		public function FlexUnitCompilerApplication()
		{
			core = new FlexUnitCore();
			core.addListener( new CIListener());
			core.addListener( new TraceListener());
			core.run( RobotlegGallaryTest );
		}
	}
}